---
- name: restart nginx
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
  become: true
  notify: reload nginx
  tags: ['nginx']
  
- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
  become: true
  tags: ['nginx']
